services:
  db:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: book_app
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - app-network
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "./setup.sh"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: book_app
      POSTGRES_PORT: 5432
      EXPRESS_PORT: 3000
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      USE_DOCKER: 1

networks:
  app-network:
    driver: bridge
